spring:
      application:
       name: demo
      datasource:
       url: jdbc:oracle:thin:@112.221.156.34:12345:xe
       username: KH08_KTY
       password: KH1234
       driver-class-name: oracle.jdbc.driver.OracleDriver

server:
      port: 80